// <auto-generated />
using System;
using FgScanner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FgScanner.Data.Migrations
{
    [DbContext(typeof(FgScannerDbContext))]
    [Migration("20260827134943_AddPageOriginalChecksum")]
    partial class AddPageOriginalChecksum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("FgScanner.Data.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomFieldsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "Sequence");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("FgScanner.Data.FieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("ListChoicesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Required")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SchemaId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Sticky")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SchemaId");

                    b.ToTable("FieldDefinitions");
                });

            modelBuilder.Entity("FgScanner.Data.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectoryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DirectoryPath")
                        .IsUnique();

                    b.HasIndex("ProfileId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("FgScanner.Data.IndexSchema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "Version")
                        .IsUnique();

                    b.ToTable("IndexSchemas");
                });

            modelBuilder.Entity("FgScanner.Data.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AiDescription")
                        .HasColumnType("TEXT");

                    b.Property<int>("AiStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageHash")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBlank")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("OcrMeanConfidence")
                        .HasColumnType("REAL");

                    b.Property<int>("OcrStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OcrText")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalChecksum")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Checksum");

                    b.HasIndex("DocumentId");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("FgScanner.Data.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AiDescriptionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BlankPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CsvDelimiter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExportCsv")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExportJson")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExportXlsx")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExportXml")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("KeepSeparatorPages")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("OcrEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OcrLanguages")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanSettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SeparatorDetectionEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("FgScanner.Data.QueuedJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PageId")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.HasIndex("State", "Type");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("FgScanner.Data.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("FgScanner.Data.TrashItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentSequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupDirectoryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OriginalGroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrashFolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeletedUtc");

                    b.ToTable("TrashItems");
                });

            modelBuilder.Entity("FgScanner.Data.Document", b =>
                {
                    b.HasOne("FgScanner.Data.Group", "Group")
                        .WithMany("Documents")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("FgScanner.Data.FieldDefinition", b =>
                {
                    b.HasOne("FgScanner.Data.IndexSchema", "Schema")
                        .WithMany("Fields")
                        .HasForeignKey("SchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schema");
                });

            modelBuilder.Entity("FgScanner.Data.Group", b =>
                {
                    b.HasOne("FgScanner.Data.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("FgScanner.Data.IndexSchema", b =>
                {
                    b.HasOne("FgScanner.Data.Profile", "Profile")
                        .WithMany("Schemas")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("FgScanner.Data.Page", b =>
                {
                    b.HasOne("FgScanner.Data.Document", "Document")
                        .WithMany("Pages")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("FgScanner.Data.QueuedJob", b =>
                {
                    b.HasOne("FgScanner.Data.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("FgScanner.Data.Document", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("FgScanner.Data.Group", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("FgScanner.Data.IndexSchema", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("FgScanner.Data.Profile", b =>
                {
                    b.Navigation("Schemas");
                });
#pragma warning restore 612, 618
        }
    }
}
